# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tlc.xdc

# Block Designs: bd/tlc/tlc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc || ORIG_REF_NAME==tlc} -quiet] -quiet

# IP: bd/tlc/ip/tlc_processing_system7_0_0/tlc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_processing_system7_0_0 || ORIG_REF_NAME==tlc_processing_system7_0_0} -quiet] -quiet

# IP: bd/tlc/ip/tlc_axi_gpio_0_0/tlc_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_axi_gpio_0_0 || ORIG_REF_NAME==tlc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/tlc/ip/tlc_xbar_0/tlc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_xbar_0 || ORIG_REF_NAME==tlc_xbar_0} -quiet] -quiet

# IP: bd/tlc/ip/tlc_ps7_0_axi_periph_0/tlc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_ps7_0_axi_periph_0 || ORIG_REF_NAME==tlc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/tlc/ip/tlc_rst_ps7_0_50M_0/tlc_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_rst_ps7_0_50M_0 || ORIG_REF_NAME==tlc_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/tlc/ip/tlc_axi_gpio_1_0/tlc_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_axi_gpio_1_0 || ORIG_REF_NAME==tlc_axi_gpio_1_0} -quiet] -quiet

# IP: bd/tlc/ip/tlc_auto_pc_0/tlc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tlc_auto_pc_0 || ORIG_REF_NAME==tlc_auto_pc_0} -quiet] -quiet

# XDC: bd/tlc/ip/tlc_processing_system7_0_0/tlc_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_processing_system7_0_0 || ORIG_REF_NAME==tlc_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_axi_gpio_0_0/tlc_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_axi_gpio_0_0 || ORIG_REF_NAME==tlc_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_axi_gpio_0_0/tlc_axi_gpio_0_0_ooc.xdc

# XDC: bd/tlc/ip/tlc_axi_gpio_0_0/tlc_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_axi_gpio_0_0 || ORIG_REF_NAME==tlc_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_rst_ps7_0_50M_0/tlc_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_rst_ps7_0_50M_0 || ORIG_REF_NAME==tlc_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_rst_ps7_0_50M_0/tlc_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_rst_ps7_0_50M_0 || ORIG_REF_NAME==tlc_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_axi_gpio_1_0/tlc_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_axi_gpio_1_0 || ORIG_REF_NAME==tlc_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_axi_gpio_1_0/tlc_axi_gpio_1_0_ooc.xdc

# XDC: bd/tlc/ip/tlc_axi_gpio_1_0/tlc_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tlc_axi_gpio_1_0 || ORIG_REF_NAME==tlc_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/tlc/ip/tlc_auto_pc_0/tlc_auto_pc_0_ooc.xdc

# XDC: bd/tlc/tlc_ooc.xdc
